export const products = [
  {
    id: 1,
    url: "https://i.ibb.co/9pc8vds/imgVime.png",
    images: [
      "https://i.ibb.co/9pc8vds/imgVime.png",
      "https://i.ibb.co/P4brdyR/font.png",
      "https://i.ibb.co/0277jFV/color1.png",
      "https://tdesigncode.online/assets/images/products/6.webp",
      "https://i.ibb.co/fXV5wK1/color2.png",
      "https://framerusercontent.com/images/E39qFeWe3gpNsjj2p8k2n69wXs.png",
      "https://i.ibb.co/F7Tg5Jf/img.png",
      "https://framerusercontent.com/images/ZLAi4FZJEHriLMrsH7DsLKMaw.png",
      "https://i.ibb.co/sPmkCPv/img-2.png",
      "https://i.ibb.co/Qfjb8GD/img-4.png",
    ],
    title: "Vime app - Giải pháp nông nghiệp",
    category: "Mobile App",
    tab: "Mobile",
    job: "UIUX Designer & React Native developer",
    description:
      "Vime App là ứng dụng chuyên biệt hỗ trợ quản lý nhà vườn, được thiết kế để tối ưu hóa quy trình quản lý và chăm sóc cây trồng. Với các tính năng như theo dõi tình trạng cây trồng, quản lý lịch tưới nước, phân bón, và ghi chép dữ liệu phát triển, Vime giúp người làm vườn dễ dàng kiểm soát và tăng cường hiệu quả sản xuất. Giao diện thân thiện cùng với các công cụ thông minh giúp đơn giản hóa công việc quản lý, đồng thời cải thiện năng suất và chất lượng cây trồng một cách bền vững.",
    tools: [
      {
        name: "Figma",
        sub: "Công cụ",
        logo: "https://i.ibb.co/d6kSyFz/figma-logo.jpg",
      },
      {
        name: "Adobe Ai",
        sub: "Công cụ",
        logo: "https://i.ibb.co/R3GnqCS/adobe-illustrator-logo.png",
      },
    ],
    logo: "https://i.ibb.co/JnKyhvJ/logo.png",
  },
  {
    id: 2,
    url: "https://framerusercontent.com/images/jHTo1pDg2S81nkJf7XPNK0KDzgk.png?scale-down-to=512",
    images: [
      "https://framerusercontent.com/images/jHTo1pDg2S81nkJf7XPNK0KDzgk.png?scale-down-to=512",
      "https://framerusercontent.com/images/9HyimqUbWfzXy4EgcKF7c6UTcmQ.png",
      "https://framerusercontent.com/images/SHOiorIUfOvA1OlVG5CdjzjQep8.png",
      "https://framerusercontent.com/images/RODqLiPPlJSpfOgG17O5dyjQo.png",
      "https://framerusercontent.com/images/kTO6E4YtFGyX86ZMnFaY2aezYw4.png",
      "https://framerusercontent.com/images/2BAMqikRW2UktLPrdYs2jNhrI.png",
    ],
    title: "Chấm công HANET",
    category: "Web App",
    tab: "Website",
    job: "UIUX Designer",
    description:
      "Một hệ thống chấm công tự động sử dụng công nghệ nhận diện khuôn mặt qua camera để ghi nhận thời gian vào và ra của nhân viên. Hệ thống giúp tiết kiệm thời gian, giảm thiểu sai sót trong việc ghi chép thủ công, và dễ dàng theo dõi thông tin chấm công theo thời gian thực. Các tính năng bao gồm nhận diện chính xác, báo cáo chi tiết và tích hợp với hệ thống quản lý nhân sự hiện có.",
    tools: [
      {
        name: "Figma",
        sub: "Công cụ",
        logo: "https://i.ibb.co/d6kSyFz/figma-logo.jpg",
      },
    ],
    logo: "https://i.ibb.co/JnKyhvJ/logo.png",
  },
  {
    id: 3,
    url: "https://i.ibb.co/JyPNmL5/image.png",
    images: [
      "https://i.ibb.co/JyPNmL5/image.png",
      "https://framerusercontent.com/images/dwmteeqjrfhenQP9nJEVJhPBOcI.png?scale-down-to=2048",
      "https://framerusercontent.com/images/UIxmeqoVPrNZVyYa1eEdNQgWg0.png?scale-down-to=1024",
      "https://framerusercontent.com/images/1GPP9QcZCCObK9Xsj2jD16ZYeB8.png?scale-down-to=1024",
      "https://framerusercontent.com/images/KMCuAx5FI0ABkulSCHa9Sww6erw.png?scale-down-to=1024",
      "https://framerusercontent.com/images/PormyvZtmTpOcR4NIaLkC3wBhg.png?scale-down-to=1024",
    ],
    title: "Hanet Karaoke",
    category: "Tablet App",
    tab: "Mobile",
    job: "UIUX Designer",
    description:
      "Phần mềm hát Hanet karaoke là một ứng dụng giải trí giúp người dùng trải nghiệm các bài hát karaoke với chất lượng âm thanh và hình ảnh vượt trội. Tích hợp kho nhạc phong phú với hàng nghìn bài hát Việt Nam và quốc tế, từ các bản hit mới nhất đến những ca khúc kinh điển. Với giao diện thân thiện và dễ sử dụng, người dùng có thể tìm kiếm và chọn bài hát nhanh chóng, điều chỉnh âm lượng, tốc độ và hiệu ứng âm thanh, tạo ra một trải nghiệm karaoke hoàn hảo.",
    tools: [
      {
        name: "Figma",
        sub: "Công cụ",
        logo: "https://i.ibb.co/d6kSyFz/figma-logo.jpg",
      },
    ],
    logo: "https://i.ibb.co/JnKyhvJ/logo.png",
  },
  {
    id: 4,
    url: "https://framerusercontent.com/images/tN3EgwXxEPdrcdOJg4anP5vzBM.png?scale-down-to=512",
    images: [
      "https://framerusercontent.com/images/tN3EgwXxEPdrcdOJg4anP5vzBM.png?scale-down-to=512",
      "https://framerusercontent.com/images/9W5truxPCnc5CBtLASEU0sHp5c.png",
      "https://framerusercontent.com/images/I8KmtsMznGyL6XNaX2X6gtnsx8.png",
      "https://framerusercontent.com/images/l988ktmcQ8v6hbu0ZdcF1rZjFSE.png",
      "https://framerusercontent.com/images/sNhyrJ3SRnvoTkhwbMCkisMOxkI.png",
      "https://framerusercontent.com/images/xVQyQNuPVc6C0GZStk5i5Jd2mec.png",
      "https://framerusercontent.com/images/s0wV92EH8JjYE9nYjt4x9i31shQ.png",
      "https://framerusercontent.com/images/GbPZ3Q1zs4fytMb2yYY4KjL0M.png",
      "https://framerusercontent.com/images/dVCBiMuvuajzEcLh0LoX8eWLEGQ.png",
      "https://framerusercontent.com/images/ppE3KrTxPJq0UrRzsv19ekrReKI.png",
      "https://framerusercontent.com/images/ej34w7JM7iDb1dbUnRq2UBvhVZY.png",
      "https://framerusercontent.com/images/gmBJVlc0SroPrUUJu4Nv35VDJE.png",
      "https://framerusercontent.com/images/UEekdddqMKOBs8iSbApyiV8DGQA.png",
      "https://framerusercontent.com/images/aQJcublFjwGngwhxQpQjWgG3eE.png",
    ],
    title: "Poho - Sàn thương mại điện tử",
    category: "Mobile App & Web App",
    tab: "Website",
    job: "UIUX Designer",
    description:
      "Sàn thương mại điện tử Poho là một nền tảng trực tuyến được thiết kế để kết nối các doanh nghiệp và người tiêu dùng, cung cấp giải pháp giao dịch và mua bán hàng hóa. Poho tập trung vào việc tối ưu hóa trải nghiệm người dùng thông qua giao diện đơn giản và dễ sử dụng, hỗ trợ các hoạt động thương mại như tìm kiếm sản phẩm, giao dịch và thanh toán trực tuyến. Với Poho, người dùng có thể dễ dàng đăng ký, mua sắm và bán hàng một cách nhanh chóng và tiện lợi.",
    tools: [
      {
        name: "Figma",
        sub: "Công cụ",
        logo: "https://i.ibb.co/d6kSyFz/figma-logo.jpg",
      },
      {
        name: "Adobe Ai",
        sub: "Công cụ",
        logo: "https://i.ibb.co/R3GnqCS/adobe-illustrator-logo.png",
      },
    ],
    logo: "https://i.ibb.co/JnKyhvJ/logo.png",
  },
  {
    id: 5,
    url: "https://framerusercontent.com/images/EQ646BOeUt4TIv2SVtf2B2lA0.png?scale-down-to=512",
    images: [
      "https://framerusercontent.com/images/EQ646BOeUt4TIv2SVtf2B2lA0.png?scale-down-to=512",
      "https://framerusercontent.com/images/eHOgUmWLuxDHfdplmayaDE8PY.png",
      "https://framerusercontent.com/images/OhqpNK1P4VIsbBvicxCzoqpIBM.png",
      "https://framerusercontent.com/images/pX8IVk6sFhrt54HVIukgD0Kolw.png",
      "https://mir-s3-cdn-cf.behance.net/project_modules/1400/11ad06135804673.61ee9a907cded.jpg",
    ],
    title: "Một số ấn phẩm thiết kế",
    category: "Graphic design",
    job: "UIUX Designer & React Native developer",
    description:
      "Sàn thương mại điện tử Poho là một nền tảng trực tuyến được thiết kế để kết nối các doanh nghiệp và người tiêu dùng, cung cấp giải pháp giao dịch và mua bán hàng hóa. Poho tập trung vào việc tối ưu hóa trải nghiệm người dùng thông qua giao diện đơn giản và dễ sử dụng, hỗ trợ các hoạt động thương mại như tìm kiếm sản phẩm, giao dịch và thanh toán trực tuyến. Với Poho, người dùng có thể dễ dàng đăng ký, mua sắm và bán hàng một cách nhanh chóng và tiện lợi.",
    tools: [
      {
        name: "Adobe Ai",
        sub: "Công cụ",
        logo: "https://i.ibb.co/R3GnqCS/adobe-illustrator-logo.png",
      },
    ],
    logo: "https://i.ibb.co/JnKyhvJ/logo.png",
  },
  {
    id: 6,
    url: "https://i.ibb.co/CnBYb6H/Mockup-2.png",
    images: [
      "https://i.ibb.co/CnBYb6H/Mockup-2.png",
      "https://i.ibb.co/fHjKQkD/Mockup-3.png",
      "https://i.ibb.co/xLn57p2/Mockup-13.png",
      "https://i.ibb.co/7tHhXhJ/Mockup-14.png",
      "https://i.ibb.co/dJW1NJ5/Mockup-15.png",
    ],
    title: "App CRM",
    category: "Mobile App",
    job: "UIUX Designer & React Native developer",
    description:
      "Vime App là ứng dụng chuyên biệt hỗ trợ quản lý nhà vườn, được thiết kế để tối ưu hóa quy trình quản lý và chăm sóc cây trồng. Với các tính năng như theo dõi tình trạng cây trồng, quản lý lịch tưới nước, phân bón, và ghi chép dữ liệu phát triển, Vime giúp người làm vườn dễ dàng kiểm soát và tăng cường hiệu quả sản xuất. Giao diện thân thiện cùng với các công cụ thông minh giúp đơn giản hóa công việc quản lý, đồng thời cải thiện năng suất và chất lượng cây trồng một cách bền vững.",
    tools: [
      {
        name: "Figma",
        sub: "Công cụ",
        logo: "https://i.ibb.co/d6kSyFz/figma-logo.jpg",
      },
      {
        name: "React Native",
        sub: "Framework",
        logo: "https://i.ibb.co/gr2hk5Y/image.png",
      },
    ],
    logo: "https://i.ibb.co/JnKyhvJ/logo.png",
  },
  {
    id: 1,
    url: "https://i.ibb.co/9pc8vds/imgVime.png",
    images: [
      "https://i.ibb.co/9pc8vds/imgVime.png",
      "https://i.ibb.co/fHjKQkD/Mockup-3.png",
      "https://framerusercontent.com/images/OhqpNK1P4VIsbBvicxCzoqpIBM.png",
      "https://cdn.dribbble.com/userupload/17349879/file/original-ba9e150c614c49d736289422d7cd66d2.png?resize=752x564&vertical=center",
      "https://i.ibb.co/F7Tg5Jf/img.png",
      "https://i.pinimg.com/736x/62/71/1e/62711ef1e80a1b149b9d0de7ac0e7d58.jpg",
      "https://i.ibb.co/sPmkCPv/img-2.png",
      "https://framerusercontent.com/images/pX8IVk6sFhrt54HVIukgD0Kolw.png",
      "https://i.ibb.co/Qfjb8GD/img-4.png",
    ],
    title: "Vime app - Giải pháp nông nghiệp",
    category: "Mobile App",
    job: "UIUX Designer & React Native developer",
    description:
      "Vime App là ứng dụng chuyên biệt hỗ trợ quản lý nhà vườn, được thiết kế để tối ưu hóa quy trình quản lý và chăm sóc cây trồng. Với các tính năng như theo dõi tình trạng cây trồng, quản lý lịch tưới nước, phân bón, và ghi chép dữ liệu phát triển, Vime giúp người làm vườn dễ dàng kiểm soát và tăng cường hiệu quả sản xuất. Giao diện thân thiện cùng với các công cụ thông minh giúp đơn giản hóa công việc quản lý, đồng thời cải thiện năng suất và chất lượng cây trồng một cách bền vững.",
    tools: [
      {
        name: "Figma",
        sub: "Công cụ",
        logo: "https://i.ibb.co/d6kSyFz/figma-logo.jpg",
      },
      {
        name: "Adobe Ai",
        sub: "Công cụ",
        logo: "https://i.ibb.co/R3GnqCS/adobe-illustrator-logo.png",
      },
    ],
    logo: "https://i.ibb.co/JnKyhvJ/logo.png",
  },
];
